#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr  4 13:37:53 2024

@author: nicooo
"""

#
# ps8pr2.py  (Problem Set 8, Problem 2)
#
# Markov text generation
#

import random

def create_dictionary(filename):
    """takes a string representing the name of a text file, and that returns a dictionary of key-value pairs in which each key is a word encountered in the text file
        the corresponding value is a list of words that follow the key word in the text file."""
    d = {}
    current_word = '$'
    
    file = open(filename)
    for line in file:
            words = line.split()
            for next_word in words:
                if current_word not in d:
                    d[current_word] = [next_word]
                else:
                    d[current_word] += [next_word]
                    
                if next_word[-1] in ('.!?'):
                    current_word = '$'
                else:
                    current_word = next_word
    return d


def generate_text(word_dict, num_words):
    """takes as parameters a dictionary of word transitions (generated by the create_dictionary function) named word_dict and a positive integer named num_words. The function must use word_dict to generate and print num_words words, with a space after each word. The function must print the words that it generates. It must not return a value"""
    current_word = '$'
    for word in range(num_words):
        wordlist = word_dict[current_word]
        next_word = random.choice(wordlist)
        print(next_word, end=' ')
        if next_word[-1] in ('.!?'):
            current_word = '$'
        else:
            current_word = next_word
    print()